version: "3"

services:
  app:
    build: .
    restart: always
    volumes:
      - ./data:/go/src/app/data
      - ./nc.db:/go/src/app/nc.db
    ports:
      - "29055:9000/tcp"
      - "23055:3000/tcp"